test:
  adapter: postgresql
  encoding: utf8
  database: canvas_test
  host: localhost
  username: postgres
  timeout: 5000

login: &login
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  username: "canvas"

# development:
#   <<: *login
#   database: canvas_development
#   queue:
#     <<: *login
#     database: canvas_queue_development

development:
  adapter: postgresql
  encoding: utf8
  database: canvas_development
  host: canvas_db_1
  username: canvas
  password: example
  timeout: 5000
  # secondary:
  #   replica: true
  #   username: canvas

# production:
#   <<: *login
#   database: canvas_production
#   queue:
#     <<: *login
#     database: canvas_queue_production
production:
  adapter: postgresql
  encoding: utf8
  database: canvas_production
  host: canvas_db_1
  username: canvas
  password: example
  timeout: 5000